# Generated by Django 4.0.1 on 2022-04-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_package_info_blessing_package_info_is_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='seller',
            field=models.CharField(blank=True, default='BBBuy', max_length=100, null=True),
        ),
    ]
