# Generated by Django 4.0.1 on 2022-01-26 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_rename_licensenum_driverprofile_license_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='image',
            field=models.ImageField(default='default.gif', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driverprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
