# Generated by Django 4.0.1 on 2022-01-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_driverprofile_vehicle_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Gold'), ('SUV', 'SUV'), ('Minivan', 'Minivan'), ('Van', 'Van')], max_length=50),
        ),
    ]
