# Generated by Django 4.0.1 on 2022-01-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_alter_ridesharer_ride_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='sharer_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Coupe', 'Gold'), ('SUV', 'SUV'), ('Minivan', 'Minivan'), ('Van', 'Van')], max_length=30),
        ),
    ]
