# Generated by Django 4.0.1 on 2022-01-31 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_alter_ridesharer_passenger_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='passenger_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_num',
            field=models.IntegerField(default=0),
        ),
    ]
