# Generated by Django 4.0.1 on 2022-04-19 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_alter_package_info_dest_x_alter_package_info_dest_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.package_info'),
        ),
    ]
