# Generated by Django 4.0.1 on 2022-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_orderinfo_sharer_name_alter_orderinfo_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='shared_seats',
            field=models.SmallIntegerField(default=0),
        ),
    ]
