# Generated by Django 4.0.1 on 2022-04-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverprofile_ups_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='dest_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='dest_y',
            field=models.IntegerField(default=0),
        ),
    ]
