# Generated by Django 4.0.1 on 2022-01-29 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_orderinfo_old_passenger_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='old_passenger_num',
            new_name='total_num',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='shared_seats',
        ),
    ]
