// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package edu.duke.ece568.amazon;

// import org.junit.Test;
// import static org.junit.Assert.*;

// public class AppTest {
//     @Test public void appHasAGreeting() {
//         App classUnderTest = new App();
//         assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//     }
// }
