# Generated by Django 4.0.1 on 2022-01-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user_email', models.CharField(default='1148201178@qq.com', max_length=50)),
                ('driver_name', models.CharField(max_length=50)),
                ('plate_num', models.CharField(max_length=20)),
                ('dest_addr', models.TextField()),
                ('arrival_date', models.DateTimeField(auto_now_add=True)),
                ('passenger_num', models.PositiveSmallIntegerField(default=1)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('special_info', models.TextField()),
                ('is_shared', models.BooleanField(default=False)),
                ('shared_seats', models.PositiveSmallIntegerField(default=0)),
                ('sharer_num', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(default='open', max_length=10)),
            ],
        ),
    ]
