# Generated by Django 4.0.1 on 2022-01-27 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0007_orderinfo_userid_alter_orderinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideowner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='special_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
