# Generated by Django 4.0.1 on 2022-01-27 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_orderinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridesharer',
            name='arrival_early',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='arrival_late',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='dest_addr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ridesharer',
            name='passenger_num',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
