# Generated by Django 4.0.1 on 2022-01-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_alter_orderinfo_passenger_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridesharer',
            name='passenger_num',
            field=models.IntegerField(default=0),
        ),
    ]
