# Generated by Django 4.0.1 on 2022-01-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverprofile_delete_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='licensenum',
            new_name='license_num',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='v_platenumber',
            new_name='plate_num',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='special_vinfo',
            new_name='special_info',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='v_capacity',
            new_name='vehicle_capacity',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='v_type',
            new_name='vehicle_type',
        ),
    ]
