# Generated by Django 4.0.1 on 2022-01-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_driverprofile_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Gold'), ('SUV', 'SUV'), ('Minivan', 'Minivan')], max_length=50),
        ),
    ]
