# Generated by Django 4.0.1 on 2022-01-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_alter_orderinfo_shared_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='old_passenger_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='passenger_num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
