# Generated by Django 4.0.1 on 2022-04-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='UPS_account',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
