# Generated by Django 4.0.1 on 2022-04-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driverprofile_dest_x_driverprofile_dest_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='dest_x',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='dest_y',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
