# Generated by Django 4.0.1 on 2022-04-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_driverprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='image',
            field=models.ImageField(default='default.gif', upload_to='profile_pics'),
        ),
    ]
