# Generated by Django 4.0.1 on 2022-01-29 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_driverprofile_image_alter_driverprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='DOB',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='ID_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
