# Generated by Django 4.0.1 on 2022-01-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driverprofile_dob_driverprofile_id_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
