# Generated by Django 4.0.1 on 2022-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_rideowner_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='userid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
