# Generated by Django 4.0.1 on 2022-01-27 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0008_rideowner_user_alter_orderinfo_special_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
