# Generated by Django 4.0.1 on 2022-01-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_rename_old_passenger_num_orderinfo_total_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='vehicle_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
