# Generated by Django 4.0.1 on 2022-04-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_commodity_commodity_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='catalog_img',
            field=models.CharField(default='/static/imgs/cart.jpeg', max_length=100),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_img',
            field=models.CharField(default='/static/imgs/cart.jpeg', max_length=100),
        ),
    ]
