# Generated by Django 4.0.1 on 2022-04-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_name', models.CharField(max_length=100)),
                ('commodity_amt', models.IntegerField(default=0)),
                ('commodity_price', models.FloatField(default=0)),
                ('commodity_catalog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.catalog')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_amt',
            new_name='commodity_amt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='commodity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopping.commodity'),
        ),
    ]
