# Generated by Django 4.0.1 on 2022-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_order_package_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='commodity_desc',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
