# Generated by Django 4.0.1 on 2022-04-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_alter_package_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='seller_email',
            field=models.CharField(blank=True, default='1148201178@qq.com', max_length=100),
        ),
    ]
