# Generated by Django 4.0.1 on 2022-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_commodity_seller_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_info',
            name='blessing',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package_info',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
