# Generated by Django 4.0.1 on 2022-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_commodity_rename_product_amt_order_commodity_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_info',
            name='dest_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package_info',
            name='dest_y',
            field=models.IntegerField(default=0),
        ),
    ]
