# Generated by Django 4.0.1 on 2022-04-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driverprofile_cardnum_driverprofile_secode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverprofile',
            old_name='secode',
            new_name='seccode',
        ),
    ]
